### ISSUE TITLE
Change wording of tweet

### ISSUE THREAD

**Issue by myself248** [i3detroit/i3Twitterbot#6]
Open-tweet should be something like "The space is now open for guests", with a trimmed timestamp (really, twitter already does timestamps), and closed-tweet should say something like "The space is now members-only (closed to guests)".

**Comment by agmlego** [comment]
Agreed on the wording issue. The timestamp is present in general because
Twitter now prevents posting duplicate statuses, but trimming the
microseconds field should be fine.
